name: Deploy Plugin

on:
    workflow_dispatch:
        inputs:
            deployment_type:
                default: 'stable'
                required: true
                type: string
                description: 'stable or testing'
            version:
                required: true
                description: 'version (e.g. 1.0.0.0)'
                type: string

jobs:
    deploy-plugin:
        runs-on: [ 'self-hosted', 'Linux', 'ARM64' ]
        uses: kalilistic/DalamudPluginDeploy/.github/workflows/deploy_plugin.yml@master
        with:
            public_name: "WhoSaidWhatNow"
            internal_name: "WhoSaidWhatNow"
            project_dir: "WhoSaidWhatNow"
            project_name: "WhoSaidWhatNow"
            github_username: "erunseelie"
            github_email: "44171274+erunseelie@users.noreply.github.com"
            open_pr: false
            deployment_type: ${{ github.event.inputs.deployment_type }}
            version: ${{ github.event.inputs.version }}
        secrets:
            DEPLOY_TOKEN: ${{ secrets.PAT }}
